// Auto-generated by FlowKit Capture
// Source: Glitch_1
// Captured: 2026-05-11T11:57:24.594Z
// Do not edit unless you know what you're doing — re-capture from AE for clean changes.

(function () {
    var EFFECT_ID   = "glitch-1";
    var EFFECT_NAME = "Glitch_1";
    var DEFAULT_FRAMES = 30;
    var CAPTURED_DURATION_S = 1.000000;
    var ALIGN_TO_END = true;

    var opts = $.flowkit.__effectOptions || {};
    var comp = app.project.activeItem;
    if (!comp || !(comp instanceof CompItem)) { $.flowkit._lastResult = "ERR: Open a composition first."; return; }
    var sel = comp.selectedLayers;
    if (!sel || sel.length === 0) { $.flowkit._lastResult = "ERR: Select at least one layer."; return; }

    var frameDur = comp.frameDuration;
    var requestedFrames = opts.durationFrames || DEFAULT_FRAMES;
    var actualDuration = requestedFrames * frameDur;
    var timeScale = CAPTURED_DURATION_S > 0 ? (actualDuration / CAPTURED_DURATION_S) : 1;
    function snapT(t) { return Math.round(t / frameDur) * frameDur; }

    var totalLayers = 0;
    var diagLines = [];
    app.beginUndoGroup("FlowKit · Apply " + EFFECT_NAME);
    try {
    for (var li = 0; li < sel.length; li++) {
        var layer = sel[li];
        var startTime;
        if (ALIGN_TO_END) {
            var endRef    = (opts.applyAt === "playhead") ? comp.time     : layer.outPoint;
            var floorRef  = (opts.applyAt === "playhead") ? 0             : layer.inPoint;
            var proposed  = endRef - actualDuration;
            if (proposed < floorRef) {
                // Not enough headroom — fall back to forward direction so
                // the animation fits within the layer (or comp).
                var forwardRef = (opts.applyAt === "playhead") ? comp.time : layer.inPoint;
                startTime = snapT(forwardRef);
            } else {
                startTime = snapT(proposed);
            }
        } else {
            var startRef = (opts.applyAt === "playhead") ? comp.time : layer.inPoint;
            startTime = snapT(startRef);
        }
        if (opts.applyMode === "replace") { $.flowkit._removePreviousApply(layer, EFFECT_ID); }

        // Diagnostic capture — surfaces in the status bar so we can see
        // exactly what the script computed at apply time.
        var _diag = {
            layer:           layer.name,
            layerIn:         (layer.inPoint  / frameDur).toFixed(1) + "f",
            layerOut:        (layer.outPoint / frameDur).toFixed(1) + "f",
            compTime:        (comp.time      / frameDur).toFixed(1) + "f",
            compDur:         (comp.duration  / frameDur).toFixed(1) + "f",
            requested:       requestedFrames + "f",
            actualDur:       (actualDuration / frameDur).toFixed(1) + "f",
            timeScale:       timeScale.toFixed(2),
            startTime:       (startTime      / frameDur).toFixed(1) + "f",
            applyAt:         (opts.applyAt   || "?"),
            applyMode:       (opts.applyMode || "?"),
            alignToEnd:      ALIGN_TO_END,
            cleanedItems:    ($.flowkit.__lastCleanupCount != null ? $.flowkit.__lastCleanupCount : 0)
        };
        $.flowkit.__lastCleanupCount = null;

        var keyframeMeta = [];
        var animatorMeta = [];
        var animatorKeyframeMeta = [];

        // ADBE Opacity
        try {
            var p0 = layer.property("ADBE Transform Group").property("ADBE Opacity");
            var t_0 = [];
            var kt0_0 = snapT(startTime + 0.633333 * timeScale);
            p0.setValueAtTime(kt0_0, 100);
            t_0.push(kt0_0);
            var kt0_1 = snapT(startTime + 0.733333 * timeScale);
            p0.setValueAtTime(kt0_1, 0);
            t_0.push(kt0_1);
            var kt0_2 = snapT(startTime + 0.900000 * timeScale);
            p0.setValueAtTime(kt0_2, 100);
            t_0.push(kt0_2);
            try { p0.setInterpolationTypeAtKey(1, KeyframeInterpolationType.BEZIER, KeyframeInterpolationType.BEZIER); } catch (e) {}
            try { p0.setTemporalEaseAtKey(1, [new KeyframeEase(0.000, 16.667)], [new KeyframeEase(-1000.000, 16.667)]); } catch (e) {}
            try { p0.setInterpolationTypeAtKey(2, KeyframeInterpolationType.BEZIER, KeyframeInterpolationType.BEZIER); } catch (e) {}
            try { p0.setTemporalEaseAtKey(2, [new KeyframeEase(-1000.000, 16.667)], [new KeyframeEase(600.000, 16.667)]); } catch (e) {}
            try { p0.setInterpolationTypeAtKey(3, KeyframeInterpolationType.BEZIER, KeyframeInterpolationType.BEZIER); } catch (e) {}
            try { p0.setTemporalEaseAtKey(3, [new KeyframeEase(600.000, 16.667)], [new KeyframeEase(0.000, 16.667)]); } catch (e) {}
            keyframeMeta.push({ prop: "ADBE Transform Group>ADBE Opacity", times: t_0 });
        } catch (e) {}

        // Text Animator: Animator 1
        try {
            var animsGroup = layer.property("ADBE Text Properties").property("ADBE Text Animators");
            var a0 = animsGroup.addProperty("ADBE Text Animator");
            var _uid0 = (Date.now ? Date.now() : new Date().getTime()).toString(36) + "_" + Math.floor(Math.random()*1000);
            var _animName0 = "FK_glitch_1_" + _uid0;
            try { a0.name = _animName0; } catch (eN) {}
            try { a0.comment = "FK:glitch_1:1"; } catch (eC) {}
            animatorMeta.push(a0.name);
            var animProps0 = a0.property("ADBE Text Animator Properties");
            var s0_0 = a0.property("ADBE Text Selectors").addProperty("ADBE Text Selector");
            try {
                var advProp = s0_0.property("ADBE Text Range Advanced").property("ADBE Text Range Shape");
                if (advProp) advProp.setValue(5);
            } catch (e) {}
            var sp0_0_0 = s0_0.property("ADBE Text Percent Start");
            var st0_0_0 = [];
            var kt0_0_0_0 = snapT(startTime + 0.000000 * timeScale);
            sp0_0_0.setValueAtTime(kt0_0_0_0, 0);
            st0_0_0.push(kt0_0_0_0);
            var kt0_0_0_1 = snapT(startTime + 0.866667 * timeScale);
            sp0_0_0.setValueAtTime(kt0_0_0_1, 100);
            st0_0_0.push(kt0_0_0_1);
            try { sp0_0_0.setInterpolationTypeAtKey(1, KeyframeInterpolationType.BEZIER, KeyframeInterpolationType.BEZIER); } catch (e) {}
            try { sp0_0_0.setTemporalEaseAtKey(1, [new KeyframeEase(0.000, 0.100)], [new KeyframeEase(0.000, 100.000)]); } catch (e) {}
            try { sp0_0_0.setInterpolationTypeAtKey(2, KeyframeInterpolationType.BEZIER, KeyframeInterpolationType.BEZIER); } catch (e) {}
            try { sp0_0_0.setTemporalEaseAtKey(2, [new KeyframeEase(0.000, 0.100)], [new KeyframeEase(0.000, 16.667)]); } catch (e) {}
            animatorKeyframeMeta.push({ animator: a0.name, selectorIdx: 1, selectorProp: "ADBE Text Percent Start", times: st0_0_0 });
            try {
                var ap0_0 = animProps0.addProperty("ADBE Text Track Type");
                ap0_0.setValue(2);
            } catch (e) {}
            try {
                var ap0_1 = animProps0.addProperty("ADBE Text Opacity");
                ap0_1.setValue(0);
            } catch (e) {}
            try {
                var ap0_2 = animProps0.addProperty("ADBE Text Tracking Amount");
                var apt0_2 = [];
                var akt0_2_0 = snapT(startTime + 0.000000 * timeScale);
                try { ap0_2.setValueAtTime(akt0_2_0, 96); apt0_2.push(akt0_2_0); } catch (eK) {}
                var akt0_2_1 = snapT(startTime + 1.000000 * timeScale);
                try { ap0_2.setValueAtTime(akt0_2_1, 0); apt0_2.push(akt0_2_1); } catch (eK) {}
                try { ap0_2.setInterpolationTypeAtKey(1, KeyframeInterpolationType.BEZIER, KeyframeInterpolationType.BEZIER); } catch (e) {}
                try { ap0_2.setTemporalEaseAtKey(1, [new KeyframeEase(0.000, 85.000)], [new KeyframeEase(0.000, 85.000)]); } catch (e) {}
                try { ap0_2.setInterpolationTypeAtKey(2, KeyframeInterpolationType.BEZIER, KeyframeInterpolationType.BEZIER); } catch (e) {}
                try { ap0_2.setTemporalEaseAtKey(2, [new KeyframeEase(0.000, 85.000)], [new KeyframeEase(0.000, 85.000)]); } catch (e) {}
                animatorKeyframeMeta.push({ animator: a0.name, selectorIdx: 0, selectorProp: "ADBE Text Tracking Amount", times: apt0_2 });
            } catch (e) {}
            try {
                var ap0_3 = animProps0.addProperty("ADBE Text Character Replace");
                ap0_3.setValue(33);
            } catch (e) {}
            try {
                var ap0_4 = animProps0.addProperty("ADBE Text Blur");
                var apt0_4 = [];
                var akt0_4_0 = snapT(startTime + 0.100000 * timeScale);
                try { ap0_4.setValueAtTime(akt0_4_0, [77,77]); apt0_4.push(akt0_4_0); } catch (eK) {}
                var akt0_4_1 = snapT(startTime + 1.000000 * timeScale);
                try { ap0_4.setValueAtTime(akt0_4_1, [0,0]); apt0_4.push(akt0_4_1); } catch (eK) {}
                try { ap0_4.setInterpolationTypeAtKey(1, KeyframeInterpolationType.BEZIER, KeyframeInterpolationType.BEZIER); } catch (e) {}
                try { ap0_4.setTemporalEaseAtKey(1, [new KeyframeEase(0.000, 80.000), new KeyframeEase(0.000, 80.000)], [new KeyframeEase(0.000, 10.000), new KeyframeEase(0.000, 10.000)]); } catch (e) {}
                try { ap0_4.setInterpolationTypeAtKey(2, KeyframeInterpolationType.BEZIER, KeyframeInterpolationType.BEZIER); } catch (e) {}
                try { ap0_4.setTemporalEaseAtKey(2, [new KeyframeEase(0.000, 80.000), new KeyframeEase(0.000, 80.000)], [new KeyframeEase(0.000, 10.000), new KeyframeEase(0.000, 10.000)]); } catch (e) {}
                animatorKeyframeMeta.push({ animator: a0.name, selectorIdx: 0, selectorProp: "ADBE Text Blur", times: apt0_4 });
            } catch (e) {}
        } catch (e) {}

        var markerInfo = null;
        if (opts.showMarker) {
            markerInfo = $.flowkit._addEffectMarker(layer, EFFECT_NAME, startTime, actualDuration, opts.keyColor);
        }

        $.flowkit._recordApply(layer, EFFECT_ID, EFFECT_NAME, {
            keyframes:         keyframeMeta,
            animators:         animatorMeta,
            animatorKeyframes: animatorKeyframeMeta,
            marker:            markerInfo,
            alignToLayerEnd:   ALIGN_TO_END
        });

        totalLayers++;
    }
    } finally { app.endUndoGroup(); }

    // Verbose diagnostic — copy-paste into chat for debugging.
    var _diagStr = "";
    if (_diag) {
        _diagStr = " | LAYER " + _diag.layer + " in=" + _diag.layerIn + " out=" + _diag.layerOut +
                   " | comp dur=" + _diag.compDur + " time=" + _diag.compTime +
                   " | requested=" + _diag.requested + " actual=" + _diag.actualDur + " scale=" + _diag.timeScale +
                   " | startTime=" + _diag.startTime + " applyAt=" + _diag.applyAt + " mode=" + _diag.applyMode +
                   " | alignToEnd=" + _diag.alignToEnd + " cleaned=" + _diag.cleanedItems;
    }
    $.flowkit._lastResult = "Applied " + EFFECT_NAME + " to " + totalLayers + " layer" + (totalLayers === 1 ? "" : "s") + _diagStr;
})();
